import type { Passage } from './game.ts';

// Original TypeRival copy written for timed play. Latin-script languages share
// the current character-based WPM model; non-Latin scripts will need their own
// fair scoring calibration before they join Ranked.
export const INTERNATIONAL_PASSAGES: Passage[] = [
  {
    id: 'es-plaza-manana',
    language: 'es',
    category: 'balanced',
    text: 'La plaza despertó con el sonido de las persianas y el aroma del café recién hecho. Un repartidor dejó cajas junto a la panadería, mientras dos vecinos comparaban el pronóstico del día. Antes de que llegara el tráfico, las mesas ya estaban listas y la fuente marcaba un ritmo tranquilo en el centro.',
  },
  {
    id: 'es-taller-bicicletas',
    language: 'es',
    category: 'balanced',
    text: 'En el taller de bicicletas, cada herramienta tenía un lugar señalado. La mecánica ajustó los frenos, limpió la cadena y giró la rueda para escuchar cualquier roce. El arreglo parecía pequeño, pero convirtió un trayecto incómodo en un paseo suave y seguro por todo el barrio.',
  },
  {
    id: 'es-sendero-bosque',
    language: 'es',
    category: 'balanced',
    text: 'El sendero entraba en el bosque después de cruzar un puente de madera. Las hojas húmedas apagaban los pasos y una señal azul indicaba el camino hacia el lago. El grupo avanzó sin prisa, atento a los cambios de luz, al canto de los pájaros y a las raíces escondidas bajo la tierra.',
  },
  {
    id: 'es-estacion-lluvia',
    language: 'es',
    category: 'balanced',
    text: 'La lluvia comenzó justo cuando el tren apareció al final de la vía. Los pasajeros cerraron sus paraguas, revisaron los números de los vagones y dejaron espacio junto a las puertas. En menos de un minuto, el andén quedó casi vacío y las luces rojas se alejaron detrás de una cortina de agua.',
  },
  {
    id: 'es-huerto-azotea',
    language: 'es',
    category: 'balanced',
    text: 'Sobre la azotea, las plantas crecían entre paredes de ladrillo y antenas. Varias personas llenaron regaderas, retiraron hojas secas y sujetaron los tomates a una cuerda. El huerto no ocultaba el ruido de la ciudad, pero ofrecía sombra, alimento y una razón sencilla para trabajar juntos.',
  },
  {
    id: 'es-faro-noche',
    language: 'es',
    category: 'balanced',
    text: 'Al caer la noche, la lente del faro comenzó a girar sobre los acantilados. La encargada anotó la fuerza del viento, comprobó la batería de respaldo y limpió la sal del cristal. Los barcos solo verían un destello constante, pero detrás de esa señal había muchas tareas pequeñas hechas con cuidado.',
  },
  {
    id: 'es-mercado-domingo',
    language: 'es',
    category: 'balanced',
    text: 'El mercado del domingo llenó la calle de colores, voces y bolsas de papel. Había frutas maduras, flores recién cortadas y panes todavía tibios. Cada vendedor conocía su mesa de memoria, y los clientes recorrían los puestos buscando una buena receta, una conversación breve o algo inesperado para llevar a casa.',
  },
  {
    id: 'es-observatorio',
    language: 'es',
    category: 'balanced',
    text: 'La cúpula del observatorio se abrió cuando las últimas nubes dejaron libre el cielo. Un motor orientó el telescopio hacia un punto que parecía vacío. Poco a poco, la pantalla reunió la luz de una galaxia distante. La imagen exigía paciencia, pero cada minuto revelaba un detalle que antes era invisible.',
  },
  {
    id: 'es-cocina-servicio',
    language: 'es',
    category: 'balanced',
    text: 'Durante el servicio, la cocina funcionaba con frases cortas y movimientos precisos. Las sartenes pasaban del fuego a la mesa, los platos esperaban bajo lámparas calientes y cada pedido se revisaba antes de salir. La velocidad importaba, aunque la coordinación siempre ahorraba más tiempo que cualquier carrera.',
  },
  {
    id: 'es-costa-viento',
    language: 'es',
    category: 'balanced',
    text: 'La carretera de la costa subía entre colinas y curvas abiertas al mar. El viento doblaba la hierba, y las olas dibujaban líneas blancas muy abajo. Una señal antigua anunciaba el próximo pueblo. El viaje duraba más que por la autopista, pero nadie elegía aquella ruta para llegar con prisa.',
  },
  {
    id: 'fr-quai-matin',
    language: 'fr',
    category: 'balanced',
    text: "Le quai s'éveillait sous une lumière pâle, bien avant l'arrivée du premier train. Des voyageurs repliaient leur journal, vérifiaient le panneau et serraient une tasse chaude entre leurs mains. Quand les portes se sont ouvertes, la foule a bougé avec calme, puis le silence est revenu le long des rails.",
  },
  {
    id: 'fr-atelier-radio',
    language: 'fr',
    category: 'balanced',
    text: "Dans l'atelier, une vieille radio attendait sous une lampe vive. Les vis étaient rangées en ligne, le fil abîmé avait été repéré et le boîtier portait encore des traces de poussière. La réparation a pris quelques minutes. Dès que la musique a rempli la pièce, tout le monde s'est arrêté pour écouter.",
  },
  {
    id: 'fr-jardin-toit',
    language: 'fr',
    category: 'balanced',
    text: "Sur le toit, des tomates grimpaient le long d'un cadre métallique au-dessus de la circulation. Les bénévoles arrosaient les herbes, attachaient les jeunes tiges et notaient la date des récoltes. Ce petit jardin ne faisait pas disparaître la ville, mais il changeait la façon de la regarder.",
  },
  {
    id: 'fr-phare-soir',
    language: 'fr',
    category: 'balanced',
    text: "Au crépuscule, la lentille du phare a commencé sa rotation régulière au-dessus des falaises. La gardienne a noté le vent, testé la batterie de secours et nettoyé le sel sur la vitre. Au large, les marins ne verraient qu'un éclat répété, sans connaître tous les gestes qui le rendaient fiable.",
  },
  {
    id: 'fr-marche-pluie',
    language: 'fr',
    category: 'balanced',
    text: "Une pluie soudaine a poussé les passants sous les auvents du marché. Les vendeurs ont couvert les paniers, rapproché les fleurs et proposé du café aux voisins. Quelques minutes plus tard, le soleil est revenu sur les pavés. Personne ne semblait pressé de quitter l'abri ni de terminer la conversation.",
  },
  {
    id: 'fr-sentier-lac',
    language: 'fr',
    category: 'balanced',
    text: "Le sentier descendait vers le lac entre des pins très hauts. Après la pluie, la terre gardait l'empreinte des animaux et les pierres brillaient sous les feuilles. Le groupe avançait lentement, non parce qu'il était perdu, mais parce que chaque détour offrait un nouveau détail à observer.",
  },
  {
    id: 'fr-cuisine-soir',
    language: 'fr',
    category: 'balanced',
    text: "Pendant le service du soir, la cuisine échangeait des phrases brèves et précises. Les casseroles passaient du feu au comptoir, les assiettes s'alignaient sous les lampes et chaque commande était vérifiée. La rapidité comptait, mais une équipe bien coordonnée gagnait toujours plus de temps qu'une personne pressée.",
  },
  {
    id: 'fr-observatoire',
    language: 'fr',
    category: 'balanced',
    text: "Le dôme de l'observatoire s'est ouvert après le départ des derniers nuages. Un moteur a guidé le télescope vers une zone sombre du ciel. Sur l'écran, une faible lumière a peu à peu dessiné une galaxie. L'image n'était ni immédiate ni parfaite, mais la patience révélait ce que l'œil seul ne pouvait voir.",
  },
  {
    id: 'fr-librairie',
    language: 'fr',
    category: 'balanced',
    text: "La petite librairie était pleine de lecteurs venus attendre la fin de l'orage. Des manteaux humides séchaient près de l'entrée tandis que chacun explorait les rayons étroits. La propriétaire conseillait ses titres préférés. Quand la pluie a cessé, plusieurs visiteurs avaient déjà oublié qu'ils voulaient repartir vite.",
  },
  {
    id: 'fr-route-cotiere',
    language: 'fr',
    category: 'balanced',
    text: "La route côtière montait au-dessus de l'eau avant de contourner de hautes falaises. À chaque point de vue, le vent couchait l'herbe et les vagues traçaient des lignes blanches en contrebas. Le trajet était plus long que par l'autoroute, mais personne ne le choisissait pour gagner quelques minutes.",
  },
  {
    id: 'de-bahnhof-morgen',
    language: 'de',
    category: 'balanced',
    text: 'Der Bahnhof wurde langsam hell, während der erste Zug in der Ferne auftauchte. Reisende prüften die Anzeige, falteten ihre Zeitungen und stellten sich hinter der gelben Linie auf. Die Türen blieben nur kurz geöffnet. Danach war der Bahnsteig wieder ruhig, und auf den Schienen lag ein leises Summen.',
  },
  {
    id: 'de-werkstatt',
    language: 'de',
    category: 'balanced',
    text: 'In der Werkstatt hatte jedes Werkzeug seinen festen Platz. Unter einer hellen Lampe lag ein altes Radio, daneben standen die Schrauben in einer sauberen Reihe. Ein lockeres Kabel war die ganze Ursache. Als wieder Musik erklang, hörten alle für einen Moment mit ihrer Arbeit auf.',
  },
  {
    id: 'de-waldweg',
    language: 'de',
    category: 'balanced',
    text: 'Der Waldweg führte über eine kleine Brücke und dann zwischen hohen Tannen bergauf. Feuchte Blätter dämpften jeden Schritt, während blaue Markierungen den Weg zum See zeigten. Die Gruppe ging aufmerksam weiter und entdeckte Spuren, Pilze und Lichtungen, die man bei größerem Tempo leicht übersehen hätte.',
  },
  {
    id: 'de-dachgarten',
    language: 'de',
    category: 'balanced',
    text: 'Auf dem Dach wuchsen Tomaten und Kräuter zwischen Mauern, Rohren und Antennen. Freiwillige trugen Wasser, entfernten trockene Blätter und banden junge Pflanzen an Schnüren fest. Der Garten machte die Stadt nicht leiser, doch er gab dem Häuserblock Farbe, Schatten und einen gemeinsamen Treffpunkt.',
  },
  {
    id: 'de-leuchtturm',
    language: 'de',
    category: 'balanced',
    text: 'Am Abend begann sich die Linse des Leuchtturms über den Klippen zu drehen. Die Wärterin notierte den Wind, prüfte die Reservebatterie und wischte Salz vom Glas. Schiffe auf dem Meer sahen nur ein regelmäßiges Licht. Dahinter standen viele kleine Kontrollen, die jede Nacht zuverlässig gemacht wurden.',
  },
  {
    id: 'de-marktplatz',
    language: 'de',
    category: 'balanced',
    text: 'Auf dem Marktplatz öffneten die Händler früh ihre Stände. Kisten mit Äpfeln, Brot und Blumen standen in langen Reihen, während die ersten Kunden ihre Taschen füllten. Zwischen kurzen Gesprächen wurden Preise notiert und neue Ware ausgepackt. Noch vor Mittag kannte jeder den Rhythmus des Tages.',
  },
  {
    id: 'de-sternwarte',
    language: 'de',
    category: 'balanced',
    text: 'Die Kuppel der Sternwarte öffnete sich, nachdem die letzten Wolken weitergezogen waren. Ein Motor richtete das Teleskop auf einen scheinbar leeren Punkt. Auf dem Bildschirm sammelte sich schwaches Licht zu einer fernen Galaxie. Geduld machte sichtbar, was das bloße Auge nicht erkennen konnte.',
  },
  {
    id: 'de-kustenstrasse',
    language: 'de',
    category: 'balanced',
    text: 'Die Küstenstraße stieg über dem Wasser an und führte in weiten Kurven um dunkle Felsen. Der Wind bog das Gras, weit unten zeichneten Wellen weiße Linien. Ein verwittertes Schild wies zum nächsten Dorf. Die Strecke dauerte länger, aber niemand fuhr hier entlang, um Zeit zu sparen.',
  },
  {
    id: 'de-bibliothek',
    language: 'de',
    category: 'balanced',
    text: 'Die Bibliothek öffnete, bevor die Stadt ganz wach war. Ein Wagen rollte leise zwischen den Regalen, und die ersten Besucher suchten ihre Plätze am Fenster. Bald lagen Notizbücher, Karten und offene Fragen auf den Tischen. Niemand eilte, trotzdem kam jede Idee Seite für Seite ein Stück weiter.',
  },
  {
    id: 'de-regentag',
    language: 'de',
    category: 'balanced',
    text: 'Regen klopfte erst langsam und dann immer schneller gegen die Fenster. Auf der Straße holten Händler ihre Schilder herein, während Fahrräder unter den Vordächern Schutz suchten. Drinnen wurde der Tee warm. Das schlechte Wetter rückte gewöhnliche Geräusche näher und machte den kleinen Raum besonders ruhig.',
  },
  {
    id: 'pt-praca-cedo',
    language: 'pt',
    category: 'balanced',
    text: 'A praça acordou com o som das portas abrindo e o cheiro de café fresco. Um entregador deixou caixas perto da padaria, enquanto vizinhos comentavam o tempo. Antes que o trânsito aumentasse, as mesas já estavam prontas e a fonte marcava um ritmo calmo no centro da manhã.',
  },
  {
    id: 'pt-oficina-bike',
    language: 'pt',
    category: 'balanced',
    text: 'Na oficina de bicicletas, cada ferramenta tinha um lugar marcado. A mecânica ajustou os freios, limpou a corrente e girou a roda para ouvir qualquer atrito. O conserto parecia pequeno, mas transformou um caminho desconfortável em um passeio suave e seguro pelas ruas do bairro.',
  },
  {
    id: 'pt-trilha-lago',
    language: 'pt',
    category: 'balanced',
    text: 'A trilha entrou na mata depois de atravessar uma ponte de madeira. Folhas úmidas abafavam os passos, e sinais azuis indicavam o caminho para o lago. O grupo avançou sem pressa, atento às mudanças de luz, ao canto dos pássaros e às raízes escondidas sob a terra.',
  },
  {
    id: 'pt-jardim-telhado',
    language: 'pt',
    category: 'balanced',
    text: 'No alto do prédio, tomates e ervas cresciam entre muros, canos e antenas. Voluntários carregavam água, retiravam folhas secas e prendiam os galhos novos com barbante. O jardim não acabava com o barulho da cidade, mas trazia sombra, alimento e um bom motivo para trabalhar em conjunto.',
  },
  {
    id: 'pt-farol-noite',
    language: 'pt',
    category: 'balanced',
    text: 'Ao anoitecer, a lente do farol começou a girar sobre as pedras altas. A responsável anotou a força do vento, testou a bateria de reserva e limpou o sal do vidro. Os barcos veriam apenas um brilho constante, sem perceber todas as pequenas tarefas que mantinham o sinal confiável.',
  },
  {
    id: 'pt-mercado-domingo',
    language: 'pt',
    category: 'balanced',
    text: 'O mercado de domingo encheu a rua de cores, vozes e sacolas de papel. Havia frutas maduras, flores recém-cortadas e pães ainda quentes. Os clientes passavam pelas bancas procurando uma receita, uma conversa rápida ou alguma surpresa simples para levar para casa.',
  },
  {
    id: 'pt-observatorio',
    language: 'pt',
    category: 'balanced',
    text: 'A cúpula do observatório se abriu quando as últimas nuvens deixaram o céu. Um motor apontou o telescópio para uma área que parecia vazia. Aos poucos, a tela reuniu a luz de uma galáxia distante. A imagem exigia paciência, mas cada minuto revelava um detalhe antes invisível.',
  },
  {
    id: 'pt-cozinha-servico',
    language: 'pt',
    category: 'balanced',
    text: 'Durante o serviço, a cozinha trabalhava com frases curtas e movimentos precisos. Panelas passavam do fogo para a bancada, pratos esperavam sob luzes quentes e cada pedido era conferido. A velocidade importava, porém uma equipe coordenada sempre economizava mais tempo do que qualquer correria.',
  },
  {
    id: 'pt-estrada-costa',
    language: 'pt',
    category: 'balanced',
    text: 'A estrada costeira subia acima do mar e contornava grandes paredões de pedra. O vento dobrava a grama, enquanto as ondas desenhavam linhas brancas lá embaixo. A viagem levava mais tempo que pela rodovia, mas ninguém escolhia aquele caminho para chegar depressa.',
  },
  {
    id: 'pt-livraria-chuva',
    language: 'pt',
    category: 'balanced',
    text: 'Uma chuva forte levou muita gente para dentro da livraria da esquina. Casacos molhados ficaram perto da porta, e os visitantes caminharam entre prateleiras estreitas. Quando o céu clareou, várias pessoas ainda folheavam novos títulos e já tinham esquecido que entraram apenas para esperar.',
  },
  {
    id: 'it-piazza-mattino',
    language: 'it',
    category: 'balanced',
    text: 'La piazza si svegliò con il rumore delle serrande e il profumo del caffè. Un fattorino lasciò alcune casse vicino al forno, mentre due vicini parlavano del tempo. Prima che aumentasse il traffico, i tavoli erano già pronti e la fontana dava un ritmo tranquillo alla mattina.',
  },
  {
    id: 'it-officina-bici',
    language: 'it',
    category: 'balanced',
    text: 'Nell’officina di biciclette, ogni attrezzo aveva un posto preciso. La meccanica regolò i freni, pulì la catena e fece girare la ruota per ascoltare ogni rumore. La riparazione sembrava piccola, ma trasformò un tragitto scomodo in una corsa fluida e sicura per tutto il quartiere.',
  },
  {
    id: 'it-sentiero-lago',
    language: 'it',
    category: 'balanced',
    text: 'Il sentiero entrava nel bosco dopo un piccolo ponte di legno. Le foglie umide rendevano silenziosi i passi, mentre i segni blu indicavano la strada verso il lago. Il gruppo avanzò senza fretta, attento alla luce, al canto degli uccelli e alle radici nascoste sotto la terra.',
  },
  {
    id: 'it-giardino-tetto',
    language: 'it',
    category: 'balanced',
    text: 'Sul tetto, pomodori ed erbe crescevano tra muri, tubi e antenne. I volontari portavano acqua, toglievano le foglie secche e legavano i rami giovani con lo spago. Il giardino non cancellava il rumore della città, ma offriva ombra, cibo e un motivo per lavorare insieme.',
  },
  {
    id: 'it-faro-sera',
    language: 'it',
    category: 'balanced',
    text: 'Al tramonto, la lente del faro iniziò a girare sopra le scogliere. La guardiana annotò il vento, controllò la batteria di riserva e pulì il sale dal vetro. Le navi avrebbero visto soltanto un lampo regolare, senza conoscere tutti i piccoli gesti che rendevano affidabile quel segnale.',
  },
  {
    id: 'it-mercato-domenica',
    language: 'it',
    category: 'balanced',
    text: 'Il mercato della domenica riempì la strada di colori, voci e sacchetti di carta. Sui banchi c’erano frutta matura, fiori appena tagliati e pane ancora caldo. I clienti passavano cercando una ricetta, una breve conversazione o una sorpresa semplice da portare a casa.',
  },
  {
    id: 'it-osservatorio',
    language: 'it',
    category: 'balanced',
    text: 'La cupola dell’osservatorio si aprì quando le ultime nuvole lasciarono libero il cielo. Un motore guidò il telescopio verso un punto che sembrava vuoto. Poco alla volta, una debole luce disegnò una galassia sullo schermo. La pazienza rivelava ciò che gli occhi non potevano vedere da soli.',
  },
  {
    id: 'it-cucina-servizio',
    language: 'it',
    category: 'balanced',
    text: 'Durante il servizio, la cucina lavorava con frasi brevi e movimenti precisi. Le pentole passavano dal fuoco al banco, i piatti aspettavano sotto le lampade e ogni ordine veniva controllato. La velocità contava, ma una squadra coordinata risparmiava sempre più tempo di una corsa confusa.',
  },
  {
    id: 'it-strada-costiera',
    language: 'it',
    category: 'balanced',
    text: 'La strada costiera saliva sopra il mare e girava intorno a scogliere scure. Il vento piegava l’erba, mentre le onde disegnavano linee bianche molto più in basso. Il viaggio durava più dell’autostrada, ma nessuno sceglieva quel percorso per arrivare in fretta.',
  },
  {
    id: 'it-libreria-pioggia',
    language: 'it',
    category: 'balanced',
    text: 'Un acquazzone improvviso spinse molte persone nella libreria all’angolo. I cappotti bagnati rimasero vicino alla porta e i visitatori esplorarono gli scaffali stretti. Quando il cielo tornò chiaro, qualcuno stava ancora leggendo e aveva dimenticato di essere entrato soltanto per aspettare.',
  },
];
