import type { Passage } from './game.ts';

// Original TypeRival summaries based on the linked primary educational sources.
// The source is shown after a run so a player can keep learning without turning
// the timed passage into a wall of citations.
export const LEARNING_PASSAGES: Passage[] = [
  {
    id: 'learn-science-webb',
    title: 'A Telescope Beyond Earth',
    language: 'en',
    category: 'science',
    sourceType: 'curated',
    text: 'The James Webb Space Telescope observes the universe from far beyond Earth. Its large mirror gathers infrared light that human eyes cannot see, helping scientists study distant galaxies, newborn stars, and the atmospheres of planets around other suns. Each observation begins as faint light and becomes evidence about how the cosmos has changed over time.',
    learning: {
      summary: 'Webb uses infrared observations to study objects ranging from forming stars to distant galaxies and exoplanets.',
      sourceLabel: 'NASA · Webb Space Telescope',
      sourceUrl: 'https://science.nasa.gov/mission/webb/',
    },
  },
  {
    id: 'learn-science-planet-variety',
    title: 'Eight Different Worlds',
    language: 'en',
    category: 'science',
    sourceType: 'curated',
    text: 'The planets in our solar system are not variations of one simple design. Some are rocky, while others are enormous worlds made mostly of gas or ice. Their temperatures, atmospheres, rings, moons, and day lengths differ widely. Comparing them gives scientists a natural laboratory for learning how planets form and why Earth developed its particular conditions.',
    learning: {
      summary: 'Comparing the solar system’s diverse planets helps researchers test ideas about planetary formation and change.',
      sourceLabel: 'NASA · Solar System Exploration',
      sourceUrl: 'https://science.nasa.gov/solar-system/planets/',
    },
  },
  {
    id: 'learn-history-constitution',
    title: 'Designing a New Government',
    language: 'en',
    category: 'history',
    sourceType: 'curated',
    text: 'In 1787, delegates met in Philadelphia to revise the young nation’s system of government. Their debates produced a new Constitution that divided power among branches and established a process for change. The document was not the end of the argument. It still had to be explained, challenged, and ratified by the states before it could take effect.',
    learning: {
      summary: 'The Constitution emerged from debate, compromise, and a separate ratification process rather than a single unanimous plan.',
      sourceLabel: 'U.S. National Archives · Constitution',
      sourceUrl: 'https://www.archives.gov/founding-docs/constitution/how-did-it-happen',
    },
  },
  {
    id: 'learn-history-web',
    title: 'A Web for Sharing Knowledge',
    language: 'en',
    category: 'history',
    sourceType: 'curated',
    text: 'While working at CERN, Tim Berners-Lee proposed a system that could connect documents across different computers. The early World Wide Web combined addresses, links, and a common way to request pages. CERN later made the software available without royalties, allowing people elsewhere to build websites and servers that could join the same growing network.',
    learning: {
      summary: 'The Web grew from open standards that let independently operated computers publish and connect information.',
      sourceLabel: 'CERN · A short history of the Web',
      sourceUrl: 'https://home.cern/science/computing/birth-web/short-history-web',
    },
  },
  {
    id: 'learn-geography-water-cycle',
    title: 'Water Is Always Moving',
    language: 'en',
    category: 'geography',
    sourceType: 'curated',
    text: 'Earth’s water moves through oceans, air, soil, rivers, ice, plants, and living things. Sunlight drives evaporation, cooling air forms clouds, and gravity returns water through rain, snow, runoff, and underground flow. A glass of water may feel still, yet it belongs to a connected planetary cycle that crosses landscapes and links weather with climate.',
    learning: {
      summary: 'The water cycle connects the atmosphere, surface water, groundwater, ice, and living systems.',
      sourceLabel: 'U.S. Geological Survey · Water Science School',
      sourceUrl: 'https://www.usgs.gov/special-topics/water-science-school/science/water-cycle',
    },
  },
  {
    id: 'learn-geography-ocean-maps',
    title: 'Mapping the Ocean Floor',
    language: 'en',
    category: 'geography',
    sourceType: 'curated',
    text: 'Most maps show coastlines clearly, but the landscape beneath the ocean is harder to observe. Research ships use sound, cameras, sensors, and remotely operated vehicles to study deep water and the seafloor. Better maps reveal mountains, trenches, habitats, and geologic activity, improving navigation while helping scientists understand a vast part of the planet.',
    learning: {
      summary: 'Ocean exploration combines mapping and direct observation to reveal seafloor geography and marine habitats.',
      sourceLabel: 'NOAA Ocean Exploration',
      sourceUrl: 'https://oceanexplorer.noaa.gov/',
    },
  },
  {
    id: 'learn-technology-internet-web',
    title: 'The Internet and the Web',
    language: 'en',
    category: 'technology',
    sourceType: 'curated',
    text: 'The internet and the World Wide Web are related, but they are not identical. The internet is the broader network that moves data between connected systems. The Web is one service built on that network, using browsers, servers, addresses, and links to exchange pages. Email, online games, and video calls can use the internet without being part of the Web.',
    learning: {
      summary: 'The internet is network infrastructure; the Web is one information system that runs on it.',
      sourceLabel: 'CERN · A short history of the Web',
      sourceUrl: 'https://home.cern/science/computing/birth-web/short-history-web',
    },
  },
  {
    id: 'learn-technology-gps',
    title: 'Timing Makes GPS Work',
    language: 'en',
    category: 'technology',
    sourceType: 'curated',
    text: 'A GPS receiver finds its position by comparing precisely timed signals from multiple satellites. Because radio signals travel at a known speed, tiny differences in arrival time help estimate distance. The receiver combines those estimates with satellite locations to calculate where it is. Navigation depends not only on maps, but also on synchronized clocks and careful mathematics.',
    learning: {
      summary: 'GPS positioning depends on satellite signals, precise timing, and distance calculations.',
      sourceLabel: 'GPS.gov · How GPS Works',
      sourceUrl: 'https://www.gps.gov/systems/gps/',
    },
  },
  {
    id: 'learn-business-market-research',
    title: 'Know the Market First',
    language: 'en',
    category: 'business',
    sourceType: 'curated',
    text: 'A business idea becomes stronger when its assumptions are tested. Market research examines potential customers, demand, location, pricing, and competing choices. Direct interviews can reveal why people behave as they do, while public data can show broader patterns. The goal is not to prove that an idea is perfect, but to reduce uncertainty before spending heavily.',
    learning: {
      summary: 'Market research blends direct customer learning with existing data to test demand and competition.',
      sourceLabel: 'U.S. Small Business Administration · Market research',
      sourceUrl: 'https://www.sba.gov/business-guide/plan-your-business/market-research-competitive-analysis',
    },
  },
  {
    id: 'learn-business-plan',
    title: 'A Plan That Can Change',
    language: 'en',
    category: 'business',
    sourceType: 'curated',
    text: 'A useful business plan explains the customer problem, the proposed solution, the way money will be earned, and the resources needed to operate. It can also describe competitors, marketing, costs, and financial expectations. The document is not a promise that every forecast will be right. It is a shared map that should improve as real evidence arrives.',
    learning: {
      summary: 'A business plan organizes a venture’s assumptions and can evolve as the team learns from customers and results.',
      sourceLabel: 'U.S. Small Business Administration · Business plans',
      sourceUrl: 'https://www.sba.gov/business-guide/plan-your-business/write-your-business-plan',
    },
  },
  {
    id: 'learn-sports-olympic-revival',
    title: 'The Modern Olympic Games',
    language: 'en',
    category: 'sports',
    sourceType: 'curated',
    text: 'Athletic festivals were held in ancient Greece, but the modern Olympic movement began much later. Organizers created an international competition inspired by that history, and the first modern Games took place in Athens in 1896. The event has continued to change as more nations, sports, and athletes joined, making today’s Games both a revival and a modern invention.',
    learning: {
      summary: 'The modern Olympics drew inspiration from ancient contests but developed as a new international movement.',
      sourceLabel: 'International Olympic Committee · Games history',
      sourceUrl: 'https://olympics.com/ioc/ancient-olympic-games/history',
    },
  },
  {
    id: 'learn-sports-recovery',
    title: 'Training Includes Recovery',
    language: 'en',
    category: 'sports',
    sourceType: 'curated',
    text: 'Improvement does not happen only during the hardest part of a workout. Rest, sleep, nutrition, and easier training days give the body time to adapt. A plan that increases effort too quickly may trade short-term excitement for fatigue or injury. Athletes build consistency by balancing challenge with recovery and by adjusting when pain or exhaustion sends a warning.',
    learning: {
      summary: 'Consistent activity is easier to sustain when training intensity grows gradually and recovery is treated as part of the plan.',
      sourceLabel: 'CDC · Physical Activity Basics',
      sourceUrl: 'https://www.cdc.gov/physical-activity/php/about/index.html',
    },
  },
  {
    id: 'learn-nature-pollinators',
    title: 'The Work of Pollinators',
    language: 'en',
    category: 'nature',
    sourceType: 'curated',
    text: 'As bees, butterflies, birds, bats, and other animals visit flowers, they can carry pollen from one bloom to another. That movement helps many plants reproduce and form seeds or fruit. Pollinators support wild habitats as well as crops people eat. Protecting them can begin with diverse native plants, fewer harmful chemicals, and places where they can feed and shelter.',
    learning: {
      summary: 'Pollinators help flowering plants reproduce and support both ecosystems and food production.',
      sourceLabel: 'National Park Service · Pollinators',
      sourceUrl: 'https://www.nps.gov/subjects/pollinators/index.htm',
    },
  },
  {
    id: 'learn-nature-wetlands',
    title: 'Why Wetlands Matter',
    language: 'en',
    category: 'nature',
    sourceType: 'curated',
    text: 'Wetlands are places where water shapes the soil and the community of plants and animals. Marshes, swamps, and similar habitats can slow floodwater, trap some pollutants, store carbon, and provide nursery areas for wildlife. They may look like empty edges between land and water, but their value comes from being connected to both.',
    learning: {
      summary: 'Wetlands provide habitat and can support water quality, flood protection, and carbon storage.',
      sourceLabel: 'U.S. Environmental Protection Agency · Wetlands',
      sourceUrl: 'https://www.epa.gov/wetlands/why-are-wetlands-important',
    },
  },
  {
    id: 'learn-health-sleep',
    title: 'Sleep Supports the Whole Day',
    language: 'en',
    category: 'health',
    sourceType: 'curated',
    text: 'Sleep is an active part of health, not simply time when nothing happens. Regular, sufficient sleep supports attention, mood, learning, and physical well-being. Helpful routines can include consistent bedtimes, a quiet and dark room, and less bright light near bedtime. Persistent sleep problems deserve attention from a qualified health professional.',
    learning: {
      summary: 'Regular, sufficient sleep supports mental and physical health; ongoing problems may need professional care.',
      sourceLabel: 'CDC · About Sleep',
      sourceUrl: 'https://www.cdc.gov/sleep/about/index.html',
    },
  },
  {
    id: 'learn-health-movement',
    title: 'Movement Adds Up',
    language: 'en',
    category: 'health',
    sourceType: 'curated',
    text: 'Physical activity does not have to arrive in one dramatic session. Walking, cycling, active play, strength work, and short movement breaks can all contribute. A sustainable routine usually fits a person’s abilities and grows gradually. Even modest increases in activity can matter, especially when they become habits that continue week after week.',
    learning: {
      summary: 'Different kinds and amounts of movement can contribute to health, and gradual routines are easier to sustain.',
      sourceLabel: 'CDC · Physical Activity Basics',
      sourceUrl: 'https://www.cdc.gov/physical-activity/php/about/index.html',
    },
  },
  {
    id: 'learn-arts-jazz',
    title: 'Jazz as Conversation',
    language: 'en',
    category: 'arts',
    sourceType: 'curated',
    text: 'Jazz developed through many communities, traditions, and individual voices. A performance may use a familiar structure while leaving room for improvisation, so musicians can respond to rhythm, harmony, and one another in the moment. The music’s history includes constant exchange and reinvention. Listening closely can reveal a conversation built from timing, memory, risk, and surprise.',
    learning: {
      summary: 'Jazz history reflects cultural exchange, while improvisation lets musicians shape a shared performance in real time.',
      sourceLabel: 'Smithsonian · Jazz',
      sourceUrl: 'https://americanhistory.si.edu/explore/projects/smithsonian-jazz',
    },
  },
  {
    id: 'learn-arts-conservation',
    title: 'Caring for Art Over Time',
    language: 'en',
    category: 'arts',
    sourceType: 'curated',
    text: 'Art conservators study materials before deciding how to protect an object. Light, moisture, temperature, insects, handling, and earlier repairs can all affect what survives. Conservation is not the same as making something look new. The work aims to slow damage, document evidence, and choose treatments carefully so future viewers and researchers can continue learning from the original piece.',
    learning: {
      summary: 'Conservation combines scientific examination, documentation, and careful treatment to preserve cultural objects.',
      sourceLabel: 'Smithsonian Museum Conservation Institute',
      sourceUrl: 'https://mci.si.edu/',
    },
  },
  {
    id: 'learn-language-change',
    title: 'Living Languages Change',
    language: 'en',
    category: 'language',
    sourceType: 'curated',
    text: 'Languages change whenever communities use them. Pronunciation shifts, new words spread, old meanings move, and grammar can develop in unexpected ways. Contact between speakers also leaves traces through borrowed words and shared patterns. These changes are not proof that a language is becoming careless. They show that people keep adapting communication to new places, tools, relationships, and ideas.',
    learning: {
      summary: 'Language change is a normal result of use, community interaction, and adaptation across generations.',
      sourceLabel: 'Linguistic Society of America · Language change',
      sourceUrl: 'https://www.linguisticsociety.org/resource/language-change',
    },
  },
  {
    id: 'learn-language-bilingual',
    title: 'More Than One Language',
    language: 'en',
    category: 'language',
    sourceType: 'curated',
    text: 'Many people use different languages or language varieties for different parts of life. A speaker may choose one at home, another at work, and a mixture among friends. Switching is often purposeful: it can express identity, fit an audience, or communicate an idea more precisely. Multilingual ability is not two separate switches, but a flexible set of connected resources.',
    learning: {
      summary: 'Multilingual speakers can draw flexibly from their languages to fit audiences, settings, identities, and ideas.',
      sourceLabel: 'Linguistic Society of America · Multilingualism',
      sourceUrl: 'https://www.linguisticsociety.org/resource/faq-what-bilingualism',
    },
  },
];
